# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebRTCExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTCExample
  pod 'GoogleWebRTC'
  pod 'IQKeyboardManagerSwift'

  target 'WebRTCExampleTests' do
    inherit! :search_paths
    pod 'GoogleWebRTC'
  end

  target 'WebRTCExampleUITests' do
    # Pods for testing
  end

end
